# Generated by Django 5.0.4 on 2024-05-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/', verbose_name='аватар'),
        ),
    ]
