# Generated by Django 5.0.4 on 2024-05-01 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletion_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
    ]
