# Generated by Django 5.0.4 on 2024-05-01 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletion_board', '0002_alter_feedback_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='author',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='author',
            new_name='owner',
        ),
    ]
